source 'https://github.com/CocoaPods/Specs.git'

target 'DNTryDriveOpenSDK_Example', :exclusive => true do
  pod 'DNTryDriveOpenSDK', :path => '../'
end

target 'DNTryDriveOpenSDK_Tests', :exclusive => true do
  pod 'DNTryDriveOpenSDK', :path => '../'
end